import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, CheckCircle2, CircleAlert, Clock3, Package, Plus, Truck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import DashboardAnalytics from '../components/DashboardAnalytics.jsx';
import DeliveryCard, { isCompletedDelivery, normalizeDeliveryStatus } from '../components/DeliveryCard.jsx';
import StatsCard from '../components/StatsCard.jsx';
import { deliveryService } from '../services/deliveryService';
import { deliveryCounts } from '../services/deliveryWorkflow.js';

const formatEta = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Not scheduled';
function Skeleton() { return <div className="card animate-pulse p-6"><div className="h-12 w-12 rounded-2xl bg-slate-100"/><div className="mt-6 h-4 w-24 rounded bg-slate-100"/><div className="mt-3 h-8 w-16 rounded bg-slate-100"/></div>; }

function Dashboard() {
  const [deliveries,setDeliveries]=useState([]); const [loading,setLoading]=useState(true); const [errorMessage,setErrorMessage]=useState(''); const [now,setNow]=useState(()=>new Date());
  useEffect(()=>{let mounted=true;deliveryService.getAllDeliveries().then(data=>mounted&&setDeliveries(data)).catch(error=>mounted&&setErrorMessage(error.message)).finally(()=>mounted&&setLoading(false));return()=>{mounted=false}},[]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),60000);return()=>window.clearInterval(timer)},[]);
  const stats=useMemo(()=>({total:deliveries.length,...deliveryCounts(deliveries)}),[deliveries]);
  const recent=useMemo(()=>[...deliveries].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0)).slice(0,6),[deliveries]);
  const dateLabel=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now); const timeLabel=new Intl.DateTimeFormat('en-IN',{hour:'2-digit',minute:'2-digit'}).format(now);
  return <div className="space-y-8">
    <motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="relative overflow-hidden rounded-3xl border border-blue-100 bg-gradient-to-br from-white via-blue-50/70 to-indigo-50 p-6 shadow-card dark:border-slate-800 dark:from-slate-900 dark:via-slate-900 dark:to-blue-950/50 sm:p-8"><div className="absolute -right-16 -top-20 h-52 w-52 rounded-full bg-blue-400/15 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-blue-600"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500"/>Live operations overview</div><h2 className="text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-4xl">Good day, Operations</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">Monitor performance, prioritize deliveries, and keep your network moving efficiently.</p></div><div className="flex items-center gap-4 sm:flex-col sm:items-end"><div className="text-left sm:text-right"><p className="text-2xl font-bold text-slate-950 dark:text-white">{timeLabel}</p><p className="mt-1 text-xs font-medium text-slate-500">{dateLabel}</p></div><Link to="/deliveries/new" className="btn-primary"><Plus size={17}/>New delivery</Link></div></div></motion.section>
    {errorMessage&&<div className="flex items-center gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700"><CircleAlert size={19}/>{errorMessage}</div>}
    <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{loading?Array.from({length:4},(_,i)=><Skeleton key={i}/>):<><StatsCard title="Total Deliveries" value={stats.total} subtitle="All delivery records" tone="blue" icon={Package} trend="Live"/><StatsCard title="Pending" value={stats.pending} subtitle="Awaiting dispatch" tone="amber" icon={Clock3} trend="Live"/><StatsCard title="In Progress" value={stats.inProgress} subtitle="Currently in transit" tone="indigo" icon={Truck} trend="Live"/><StatsCard title="Completed" value={stats.completed} subtitle="Successfully delivered" tone="green" icon={CheckCircle2} trend="Live"/></>}</div>
    {!loading&&<DashboardAnalytics deliveries={deliveries}/>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,.7fr)]"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5 sm:px-6"><div><h3 className="font-bold text-slate-950">Recent deliveries</h3><p className="mt-1 text-xs text-slate-500">Latest activity across your network</p></div><Link to="/deliveries" className="flex items-center gap-1 text-sm font-semibold text-blue-600 hover:text-blue-700">View all <ArrowRight size={15}/></Link></div><div className="p-4 sm:p-6">{loading?<div className="grid gap-4 xl:grid-cols-2"><Skeleton/><Skeleton/></div>:recent.length?<div className="grid gap-4 xl:grid-cols-2">{recent.map(d=><DeliveryCard key={d.id} customer={d.customerName} address={d.deliveryAddress} priority={d.priority} status={d.status} eta={formatEta(d.estimatedDeliveryTime)} completedAt={d.completedAt?formatEta(d.completedAt):''}/>)}</div>:<div className="py-14 text-center"><Truck className="mx-auto text-slate-300" size={40}/><h4 className="mt-4 font-bold text-slate-900">No deliveries yet</h4><p className="mt-1 text-sm text-slate-500">Create your first delivery to populate the dashboard.</p></div>}</div></section>
      <aside className="card p-6"><h3 className="font-bold text-slate-950">Activity feed</h3><p className="mt-1 text-xs text-slate-500">Recent operational events</p><div className="mt-6">{recent.slice(0,5).map((delivery,index)=>{const completed=isCompletedDelivery(delivery.status);return <div key={delivery.id} className="relative flex gap-3 pb-6"><div className={`relative z-10 mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${completed?'bg-emerald-50 text-emerald-600':'bg-blue-50 text-blue-600'}`}>{completed?<CheckCircle2 size={17}/>:<Truck size={17}/>}</div>{index<Math.min(recent.length,5)-1&&<div className="absolute left-[17px] top-9 h-[calc(100%-34px)] w-px bg-slate-200 dark:bg-slate-700"/>}<div><p className="text-sm font-semibold text-slate-900">{delivery.customerName}</p><p className="mt-1 text-xs leading-5 text-slate-500">{completed?'Delivery completed':'Delivery added to operations'}</p><p className="mt-1 text-[11px] font-medium text-slate-400">{formatEta(completed&&delivery.completedAt?delivery.completedAt:delivery.estimatedDeliveryTime)}</p></div></div>})}{!recent.length&&!loading&&<p className="py-12 text-center text-sm text-slate-500">Activity will appear here.</p>}</div></aside>
    </div>
  </div>;
}
export default Dashboard;
