import { useEffect, useRef, useState } from 'react';
import { motion, useInView, useMotionValue, useSpring, useTransform } from 'framer-motion';
import { ArrowRight, BarChart3, Check, ChevronLeft, ChevronRight, Code2, LockKeyhole, Mail, Map, MapPin, Menu, Moon, Network, PackageCheck, Route, ShieldCheck, Smartphone, Sparkles, Sun, Truck, X, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';
import { SiAxios, SiGithub, SiLeaflet, SiMysql, SiOpenjdk, SiReact, SiSpringboot, SiSpringsecurity, SiTailwindcss } from 'react-icons/si';
import { useTheme } from '../hooks/useTheme.js';
import dashboardImage from '../assets/screenshots/dashboard.png';
import deliveriesImage from '../assets/screenshots/deliveries.png';
import routeOptimizerImage from '../assets/screenshots/route-optimizer.png';
import routeMapImage from '../assets/screenshots/route-map.png';
import loginImage from '../assets/screenshots/login.png';
import registerImage from '../assets/screenshots/register.png';

const reveal = { initial: { opacity: 0, y: 28 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-80px' }, transition: { duration: .6, ease: [0.22, 1, 0.36, 1] } };
const features = [
  [ShieldCheck,'Secure Authentication','Role-aware access powered by Spring Security and protected REST services.'],
  [PackageCheck,'Delivery Management','Create, organize, prioritize, and monitor every delivery from one workspace.'],
  [BarChart3,'Dashboard Analytics','Understand delivery status, priorities, trends, and completion at a glance.'],
  [Network,'Graph Algorithms','Model delivery locations as a weighted graph for intelligent route planning.'],
  [Route,'Shortest Path Optimization','Apply Dijkstra’s Algorithm to find efficient paths between delivery stops.'],
  [Map,'Interactive Maps','Explore optimized routes and stops visually with React Leaflet mapping.'],
  [Smartphone,'Responsive Design','A consistent premium experience across desktop, tablet, and mobile.'],
  [Code2,'REST APIs','A clean React and Spring Boot integration built around reliable REST endpoints.'],
];
const tech = [
  [SiReact,'React','#61dafb'],[SiSpringboot,'Spring Boot','#6db33f'],[SiOpenjdk,'Java','#f89820'],[SiMysql,'MySQL','#4479a1'],[SiTailwindcss,'Tailwind CSS','#06b6d4'],[SiLeaflet,'React Leaflet','#199900'],[SiAxios,'Axios','#5a29e4'],[SiSpringsecurity,'Spring Security','#6db33f'],[Network,'Graph Algorithms','#2563eb'],[Route,'Dijkstra','#4f46e5'],
];
const steps = [[LockKeyhole,'Login','Access the secure operations workspace.'],[PackageCheck,'Add Deliveries','Capture destinations, priorities, and delivery details.'],[Zap,'Optimize Route','Generate an efficient sequence using graph algorithms.'],[MapPin,'View Interactive Map','Inspect every optimized stop on a live route map.']];
const gallery = [['Dashboard',dashboardImage],['Delivery Management',deliveriesImage],['Route Optimizer',routeOptimizerImage],['Interactive Map',routeMapImage],['Login',loginImage],['Register',registerImage]];

function SectionHeading({ eyebrow, title, copy }) { return <motion.div {...reveal} className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">{eyebrow}</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 dark:text-white sm:text-5xl">{title}</h2><p className="mt-5 text-sm leading-7 text-slate-500 sm:text-base">{copy}</p></motion.div>; }

function Counter({ value, suffix='' }) { const ref=useRef(null); const visible=useInView(ref,{once:true}); const number=useMotionValue(0); const spring=useSpring(number,{duration:1500,bounce:0}); const rounded=useTransform(spring,(latest)=>Math.round(latest)); useEffect(()=>{if(visible)number.set(value)},[visible,number,value]); return <span ref={ref}><motion.span>{rounded}</motion.span>{suffix}</span>; }

function LandingPage() {
  const { theme,toggleTheme }=useTheme(); const [menuOpen,setMenuOpen]=useState(false); const galleryRef=useRef(null);
  const scrollGallery=(direction)=>galleryRef.current?.scrollBy({left:direction*520,behavior:'smooth'});
  return <div className="min-h-screen overflow-x-hidden bg-white text-slate-950 transition-colors dark:bg-[#070b14] dark:text-white">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/75 backdrop-blur-2xl dark:border-slate-800 dark:bg-slate-950/70"><nav className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 py-3.5 sm:px-8"><a href="#top" className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 font-black text-white shadow-lg shadow-blue-500/25">SD</span><span><b className="block text-sm">Smart Delivery</b><span className="block text-[10px] font-semibold uppercase tracking-wider text-slate-500">Route Optimizer</span></span></a><div className="hidden items-center gap-8 lg:flex"><a href="#features" className="text-sm font-semibold text-slate-600 transition hover:text-blue-600 dark:text-slate-300">Features</a><a href="#technology" className="text-sm font-semibold text-slate-600 transition hover:text-blue-600 dark:text-slate-300">Technology</a><a href="#about" className="text-sm font-semibold text-slate-600 transition hover:text-blue-600 dark:text-slate-300">About</a></div><div className="hidden items-center gap-2 lg:flex"><button onClick={toggleTheme} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 text-slate-500 transition hover:bg-slate-100 dark:border-slate-700 dark:hover:bg-slate-800" aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><Link to="/login" className="btn-secondary">Login</Link><Link to="/register" className="btn-primary">Get started <ArrowRight size={16}/></Link></div><button onClick={()=>setMenuOpen(v=>!v)} className="rounded-xl border border-slate-200 p-2.5 lg:hidden dark:border-slate-700" aria-label="Toggle menu">{menuOpen?<X/>:<Menu/>}</button></nav>{menuOpen&&<motion.div initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} className="border-t border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950 lg:hidden"><div className="grid gap-2">{[['Features','#features'],['Technology','#technology'],['About','#about']].map(([label,url])=><a key={url} href={url} onClick={()=>setMenuOpen(false)} className="rounded-xl px-4 py-3 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-slate-800">{label}</a>)}<div className="mt-2 flex gap-2"><button onClick={toggleTheme} className="btn-secondary px-3">{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><Link to="/login" className="btn-secondary flex-1">Login</Link><Link to="/register" className="btn-primary flex-1">Get started</Link></div></div></motion.div>}</header>

    <main id="top"><section className="relative flex min-h-screen items-center overflow-hidden pb-20 pt-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_20%,rgba(37,99,235,.13),transparent_28%),radial-gradient(circle_at_85%_35%,rgba(79,70,229,.12),transparent_30%)]"/><motion.div animate={{y:[0,-18,0],rotate:[0,4,0]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}} className="absolute left-[8%] top-32 h-24 w-24 rounded-[2rem] border border-blue-200/60 bg-blue-400/10 backdrop-blur dark:border-blue-500/20"/><motion.div animate={{y:[0,22,0],rotate:[0,-6,0]}} transition={{duration:10,repeat:Infinity,ease:'easeInOut'}} className="absolute bottom-24 right-[6%] h-32 w-32 rounded-full bg-indigo-500/10 blur-sm"/><div className="relative mx-auto grid w-full max-w-7xl items-center gap-14 px-5 sm:px-8 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{opacity:0,x:-35}} animate={{opacity:1,x:0}} transition={{duration:.75,ease:[.22,1,.36,1]}}><span className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50/80 px-3.5 py-2 text-xs font-bold text-blue-700 shadow-sm backdrop-blur dark:border-blue-500/20 dark:bg-blue-500/10 dark:text-blue-300"><Sparkles size={14}/>Graph-powered delivery intelligence</span><h1 className="mt-7 text-5xl font-black leading-[1.03] tracking-[-.045em] text-slate-950 dark:text-white sm:text-6xl xl:text-7xl">Smart Delivery<br/><span className="bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 bg-clip-text text-transparent">Route Optimizer</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-slate-600 dark:text-slate-300 sm:text-lg">Optimize delivery routes intelligently using Graph Algorithms, Dijkstra&apos;s Algorithm, and Real-Time Mapping.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="btn-primary px-6 py-3.5">Get started <ArrowRight size={18}/></Link><Link to="/login" className="btn-secondary px-6 py-3.5">Login to dashboard</Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-semibold text-slate-500">{['Secure operations','Real-time mapping','Algorithmic routing'].map(item=><span key={item} className="flex items-center gap-2"><Check size={15} className="text-emerald-500"/>{item}</span>)}</div></motion.div>
      <motion.div initial={{opacity:0,scale:.9,y:30}} animate={{opacity:1,scale:1,y:0}} transition={{delay:.2,duration:.8}} className="relative"><div className="absolute -inset-8 rounded-full bg-blue-500/15 blur-3xl"/><div className="relative rounded-[2rem] border border-white/70 bg-white/55 p-4 shadow-[0_35px_100px_rgba(37,99,235,.18)] backdrop-blur-2xl dark:border-white/10 dark:bg-slate-900/55"><div className="rounded-3xl border border-slate-200/70 bg-white p-5 dark:border-slate-700 dark:bg-slate-900"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white"><Truck size={20}/></span><div><b className="block text-sm">Route intelligence</b><span className="text-[11px] text-slate-500">Optimization in progress</span></div></div><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-500"/></div><div className="relative mt-7 h-72 overflow-hidden rounded-2xl bg-gradient-to-br from-blue-50 to-indigo-50 dark:from-slate-800 dark:to-blue-950"><svg viewBox="0 0 500 280" className="absolute inset-0 h-full w-full"><motion.path d="M55 220 C120 140,150 190,215 110 S340 160,445 55" fill="none" stroke="#2563eb" strokeWidth="5" strokeLinecap="round" strokeDasharray="10 10" initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:2,delay:.7}}/></svg>{[[12,72],[41,37],[70,50],[88,16]].map(([left,top],i)=><motion.div key={i} initial={{scale:0}} animate={{scale:1}} transition={{delay:.8+i*.18,type:'spring'}} className="absolute flex h-10 w-10 items-center justify-center rounded-full border-4 border-white bg-gradient-to-br from-blue-600 to-indigo-600 text-xs font-bold text-white shadow-lg dark:border-slate-900" style={{left:`${left}%`,top:`${top}%`}}>{i+1}</motion.div>)}<motion.div animate={{x:[0,22,0]}} transition={{duration:3,repeat:Infinity}} className="absolute bottom-5 left-5 rounded-xl border border-white/70 bg-white/85 px-3 py-2 text-xs font-bold text-slate-700 shadow-lg backdrop-blur dark:border-slate-700 dark:bg-slate-900/90 dark:text-white"><Truck className="mr-2 inline text-blue-600" size={16}/>12.8 km optimized</motion.div></div></div></div></motion.div></div></section>

    <section id="features" className="bg-slate-50/70 py-24 dark:bg-slate-900/30 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHeading eyebrow="Powerful capabilities" title="Everything your delivery operation needs" copy="A complete engineering solution combining modern web technology, secure services, intelligent algorithms, and interactive geospatial experiences."/><div className="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,copy],index)=><motion.article key={title} {...reveal} transition={{...reveal.transition,delay:index*.04}} whileHover={{y:-8,scale:1.015}} className="group rounded-3xl border border-slate-200/80 bg-white p-6 shadow-card transition dark:border-slate-800 dark:bg-slate-900"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-blue-600 to-indigo-600 text-white shadow-lg shadow-blue-500/20 transition group-hover:scale-110"><Icon size={22}/></div><h3 className="mt-6 font-bold text-slate-950 dark:text-white">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></motion.article>)}</div></div></section>

    <section id="technology" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHeading eyebrow="Technology stack" title="Built with modern, production-ready tools" copy="A carefully selected full-stack architecture for performance, security, maintainability, and elegant user experiences."/><div className="mt-16 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{tech.map(([Icon,title,color],index)=><motion.div key={title} {...reveal} transition={{...reveal.transition,delay:index*.035}} whileHover={{y:-6}} className="rounded-2xl border border-slate-200 bg-white p-5 text-center shadow-sm dark:border-slate-800 dark:bg-slate-900"><Icon className="mx-auto text-4xl" style={{color}}/><p className="mt-4 text-sm font-bold text-slate-800 dark:text-slate-100">{title}</p></motion.div>)}</div></div></section>

    <section className="bg-slate-950 py-24 text-white sm:py-32"><div className="mx-auto max-w-6xl px-5 sm:px-8"><SectionHeading eyebrow="Simple workflow" title="From delivery details to the optimal route" copy="Four clear steps transform raw delivery information into an actionable route on an interactive map."/><div className="relative mt-16 grid gap-8 md:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-7 hidden h-px bg-gradient-to-r from-transparent via-blue-500 to-transparent md:block"/>{steps.map(([Icon,title,copy],index)=><motion.div key={title} {...reveal} transition={{...reveal.transition,delay:index*.12}} className="relative text-center"><div className="relative z-10 mx-auto flex h-14 w-14 items-center justify-center rounded-2xl border border-blue-400/30 bg-blue-500/15 text-blue-300 shadow-lg shadow-blue-950"><Icon size={23}/><span className="absolute -right-2 -top-2 flex h-6 w-6 items-center justify-center rounded-full bg-white text-[10px] font-black text-slate-950">{index+1}</span></div><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-xs leading-5 text-slate-400">{copy}</p></motion.div>)}</div></div></section>

    <section className="py-20"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-4 px-5 sm:px-8 lg:grid-cols-4">{[[100,'Responsive','%'],[10,'REST APIs','+'],[4,'Major Algorithms',''],[7,'Major Modules','']].map(([value,label,suffix])=><motion.div key={label} {...reveal} className="rounded-3xl border border-slate-200 bg-gradient-to-br from-white to-blue-50 p-6 text-center shadow-card dark:border-slate-800 dark:from-slate-900 dark:to-blue-950/30"><p className="text-4xl font-black text-blue-600"><Counter value={value} suffix={suffix}/></p><p className="mt-2 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p></motion.div>)}</div></section>

    <section className="overflow-hidden bg-slate-50/70 py-24 dark:bg-slate-900/30 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-600">Product gallery</p><h2 className="mt-4 text-3xl font-bold tracking-tight dark:text-white sm:text-5xl">See the platform in action</h2><p className="mt-4 text-sm leading-7 text-slate-500">Explore the real application screens built for this project.</p></div><div className="flex gap-2"><button onClick={()=>scrollGallery(-1)} className="btn-secondary h-11 w-11 p-0" aria-label="Previous screenshots"><ChevronLeft/></button><button onClick={()=>scrollGallery(1)} className="btn-secondary h-11 w-11 p-0" aria-label="Next screenshots"><ChevronRight/></button></div></div><div ref={galleryRef} className="mt-12 flex snap-x snap-mandatory gap-6 overflow-x-auto pb-6 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{gallery.map(([title,image])=><motion.figure key={title} whileHover={{y:-6}} className="min-w-[88%] snap-center overflow-hidden rounded-3xl border border-slate-200 bg-white p-3 shadow-card dark:border-slate-800 dark:bg-slate-900 sm:min-w-[620px]"><div className="overflow-hidden rounded-2xl bg-slate-100"><img src={image} alt={`${title} application screenshot`} loading="lazy" className="aspect-video w-full object-cover object-top transition duration-700 hover:scale-[1.02]"/></div><figcaption className="flex items-center justify-between px-3 py-4"><b className="text-sm">{title}</b><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">Product view</span></figcaption></motion.figure>)}</div></div></section>

    <section id="about" className="py-24 sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8"><SectionHeading eyebrow="About the project" title="Engineering smarter last-mile delivery" copy="A final year engineering project designed to demonstrate how algorithms, modern software architecture, and thoughtful product design can solve practical logistics challenges."/><div className="mt-16 grid gap-5 md:grid-cols-2">{[['Purpose','Build an intelligent, full-stack platform that makes route planning understandable, accessible, and efficient.'],['Problem Solved','Reduce inefficient delivery sequencing, fragmented tracking, and the manual effort needed to plan multiple stops.'],['Benefits','Faster planning, improved operational visibility, clearer prioritization, and interactive spatial decision-making.'],['Future Scope','Live traffic data, driver tracking, vehicle capacity planning, multi-depot routing, and predictive delivery insights.']].map(([title,copy],index)=><motion.article key={title} {...reveal} transition={{...reveal.transition,delay:index*.06}} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-card dark:border-slate-800 dark:bg-slate-900"><span className="text-xs font-black text-blue-600">0{index+1}</span><h3 className="mt-4 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-500">{copy}</p></motion.article>)}</div></div></section>
    </main>

    <footer className="border-t border-slate-200 bg-slate-50 py-12 dark:border-slate-800 dark:bg-slate-950"><div className="mx-auto flex max-w-7xl flex-col gap-8 px-5 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-indigo-600 font-black text-white">SD</span><div><b className="text-sm">Smart Delivery Route Optimizer</b><p className="mt-1 text-xs text-slate-500">Designed and developed by Mohd Azaan Javed</p></div></div><div className="flex flex-wrap gap-2"><a href="https://github.com/mohdazaanjaved-eng/smart-delivery-route-optimizer" target="_blank" rel="noreferrer" className="btn-secondary"><SiGithub size={17}/>GitHub</a><a href="mailto:mohdazaanjaved@gmail.com" className="btn-secondary"><Mail size={17}/>Contact</a><a href="#top" className="btn-primary">Back to top <ChevronRight className="-rotate-90" size={17}/></a></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-slate-200 px-5 pt-6 text-xs text-slate-500 dark:border-slate-800 sm:px-8">© 2026 Smart Delivery Route Optimizer. Final Year Engineering Project.</div></footer>
  </div>;
}
export default LandingPage;
