import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, MapPinned, Route, ShieldCheck, Sparkles } from 'lucide-react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { authService } from '../services/authService';
function Login(){const navigate=useNavigate();const location=useLocation();const [formData,setFormData]=useState({email:'',password:''});const [error,setError]=useState('');const [validation,setValidation]=useState({});const [loading,setLoading]=useState(false);const [show,setShow]=useState(false);
const change=e=>{const{name,value}=e.target;setFormData(c=>({...c,[name]:value}));setValidation(c=>({...c,[name]:undefined}))};
const submit=async e=>{e.preventDefault();setLoading(true);setError('');setValidation({});try{await authService.login(formData);toast.success('Welcome back');navigate('/dashboard',{replace:true})}catch(err){setError(err.message);setValidation(err.validationErrors||{})}finally{setLoading(false)}};
return <main className="grid min-h-screen bg-white lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-slate-950 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -left-24 top-1/3 h-80 w-80 rounded-full bg-blue-600/30 blur-3xl"/><div className="absolute -right-20 -top-20 h-80 w-80 rounded-full bg-indigo-600/30 blur-3xl"/><div className="relative flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-600 shadow-lg shadow-blue-600/30"><MapPinned/></div><div><p className="font-bold">Smart Delivery</p><p className="text-xs text-slate-400">Route Optimizer</p></div></div><div className="relative max-w-xl"><span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs font-semibold text-blue-200"><Sparkles size={14}/>Intelligent logistics platform</span><h1 className="mt-6 text-5xl font-bold leading-[1.1] tracking-tight">Deliver smarter.<br/><span className="text-blue-400">Route faster.</span></h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300">One premium workspace to manage deliveries, monitor priorities, and optimize every route.</p><div className="mt-10 grid grid-cols-2 gap-4"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><Route className="text-blue-400"/><p className="mt-3 text-sm font-bold">Optimized routing</p><p className="mt-1 text-xs text-slate-400">Efficient stop sequencing</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><ShieldCheck className="text-emerald-400"/><p className="mt-3 text-sm font-bold">Secure operations</p><p className="mt-1 text-xs text-slate-400">Protected delivery data</p></div></div></div><p className="relative text-xs text-slate-500">Final Year Engineering Project · 2026</p></section>
<section className="flex items-center justify-center px-6 py-12 sm:px-10"><div className="w-full max-w-md"><div className="mb-9 lg:hidden"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 text-white"><MapPinned/></div></div><p className="text-sm font-semibold text-blue-600">Welcome back</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Sign in to your account</h2><p className="mt-2 text-sm text-slate-500">Manage delivery operations from your workspace.</p>{location.state?.message&&<div className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm font-medium text-emerald-700">{location.state.message}</div>}{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">{error}</div>}
<form className="mt-8 space-y-5" onSubmit={submit}><label className="block"><span className="text-sm font-semibold text-slate-700">Email address</span><div className="relative mt-2"><Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="input pl-11" type="email" name="email" value={formData.email} onChange={change} placeholder="admin@example.com" autoComplete="email"/></div>{validation.email&&<p className="mt-1.5 text-xs font-medium text-red-600">{validation.email}</p>}</label><label className="block"><span className="text-sm font-semibold text-slate-700">Password</span><div className="relative mt-2"><LockKeyhole className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input className="input px-11" type={show?'text':'password'} name="password" value={formData.password} onChange={change} placeholder="Enter your password" autoComplete="current-password"/><button type="button" onClick={()=>setShow(v=>!v)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-1 text-slate-400 hover:text-slate-700" aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{validation.password&&<p className="mt-1.5 text-xs font-medium text-red-600">{validation.password}</p>}</label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2 text-slate-600"><input type="checkbox" className="h-4 w-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500"/>Remember me</label><button type="button" className="font-semibold text-blue-600 hover:text-blue-700">Forgot password?</button></div><button disabled={loading} className="btn-primary w-full py-3">{loading?'Signing in...':<>Sign in <ArrowRight size={17}/></>}</button></form><p className="mt-7 text-center text-sm text-slate-500">New to Smart Delivery? <Link className="font-bold text-blue-600 hover:text-blue-700" to="/register">Create an account</Link></p></div></section></main>}
export default Login;
