import { useState } from 'react';
import { Clock3, Loader2, MapPinned, Navigation, Route, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';
import RouteCard from '../components/RouteCard.jsx';
import RouteMap from '../components/RouteMap.jsx';
import StatsCard from '../components/StatsCard.jsx';
import { routeService } from '../services/routeService';
const emptyRoute={totalDistance:0,totalStops:0,route:[]}; const fmt=(v)=>Number(v||0).toFixed(2);
function RouteOptimizer(){const [optimizedRoute,setOptimizedRoute]=useState(emptyRoute);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [hasOptimized,setHasOptimized]=useState(false);
const optimize=async()=>{setLoading(true);setError('');try{const data=await routeService.optimizeRoute();setOptimizedRoute(data);setHasOptimized(true);toast.success('Route optimized successfully')}catch(e){setError(e.message);toast.error(e.message)}finally{setLoading(false)}};
const estimatedMinutes=Math.round(Number(optimizedRoute.totalDistance||0)*2.5+Number(optimizedRoute.totalStops||0)*5);
return <div className="space-y-7"><section className="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-8 text-white shadow-2xl sm:px-10 sm:py-10"><div className="absolute -right-20 -top-32 h-80 w-80 rounded-full bg-blue-600/30 blur-3xl"/><div className="absolute bottom-0 left-1/3 h-40 w-40 rounded-full bg-indigo-500/20 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 lg:flex-row lg:items-center"><div className="max-w-2xl"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10 ring-1 ring-white/15"><MapPinned size={22}/></div><h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Intelligent route optimizer</h2><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Turn pending deliveries into the most efficient stop sequence with a single click.</p></div><button onClick={optimize} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3.5 text-sm font-bold text-slate-950 shadow-xl transition hover:-translate-y-1 hover:bg-blue-50 disabled:pointer-events-none disabled:opacity-70">{loading?<><Loader2 className="animate-spin" size={18}/>Optimizing route...</>:<><Sparkles size={18} className="text-blue-600"/>Optimize route</>}</button></div></section>
{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div>}
<div className="grid gap-4 md:grid-cols-3"><StatsCard title="Total Stops" value={optimizedRoute.totalStops} subtitle="Stops in optimized sequence" tone="blue" icon={MapPinned}/><StatsCard title="Total Distance" value={`${fmt(optimizedRoute.totalDistance)} km`} subtitle="Projected travel distance" tone="indigo" icon={Navigation}/><StatsCard title="Estimated Time" value={`${estimatedMinutes} min`} subtitle="Travel and service estimate" tone="green" icon={Clock3}/></div>
{loading?<div className="card flex min-h-72 flex-col items-center justify-center"><Loader2 className="animate-spin text-blue-600" size={34}/><p className="mt-4 text-sm font-semibold text-slate-700">Calculating the optimal sequence...</p><p className="mt-1 text-xs text-slate-500">Analyzing pending stops and distances</p></div>:optimizedRoute.route.length===0?<div className="card flex min-h-72 flex-col items-center justify-center p-8 text-center"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Route size={30}/></div><h3 className="mt-4 font-bold text-slate-950">{hasOptimized?'No pending stops found':'Ready to optimize'}</h3><p className="mt-2 max-w-md text-sm text-slate-500">{hasOptimized?'All deliveries are currently handled.':'Click Optimize Route to generate the best delivery sequence from the latest backend data.'}</p></div>:<div className="grid items-start gap-6 xl:grid-cols-[400px_minmax(0,1fr)]"><section className="card max-h-[590px] overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h3 className="font-bold text-slate-950">Optimized timeline</h3><p className="mt-1 text-xs text-slate-500">{optimizedRoute.route.length} stops in visit order</p></div><div className="max-h-[510px] overflow-y-auto p-5">{optimizedRoute.route.map((s,i)=><RouteCard key={`${s.order}-${s.customer}`} order={s.order} customer={s.customer} address={s.address} distance={fmt(s.distanceFromPrevious)} isLast={i===optimizedRoute.route.length-1}/>)}</div></section><RouteMap stops={optimizedRoute.route}/></div>}</div>}
export default RouteOptimizer;
